Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -43,10 +43,14 @@ jobs:
          ./gradlew assembleRelease  --stacktrace
          ./gradlew bundleRelease
     - name: Release to RuStore
+      env:
+        KEY_ID: ${{ secrets.RUSTORE_KEY_ID }}
+        PRIVATE_KEY_BASE64: ${{ secrets.RUSTORE_KEY }}
       run: |
-        KEY_ID="${{ secrets.RUSTORE_KEY_ID }}"
+        APP_PACKAGE_NAME="top.rootu.lampa" # пакет приложения
+        APK_PATH="./app/build/outputs/apk/ruStore/release/app-ruStore-release.apk" # Путь к APK
+        VERSION_CODE=$(git rev-list --count origin/main) # versionCode
         # Извлекаем приватный ключ из секрета и декодируем
-        PRIVATE_KEY_BASE64="${{ secrets.RUSTORE_KEY }}"
         echo $PRIVATE_KEY_BASE64 | base64 --decode > private_key.pem
         # Генерация timestamp
         TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%S%z")
@@ -54,7 +58,7 @@ jobs:
         MESSAGE="${KEY_ID}${TIMESTAMP}"
         # Генерация подписи с помощью OpenSSL
         SIGNATURE=$(echo -n "$MESSAGE" | openssl dgst -sha512 -sign private_key.pem | base64)
-        echo "Signature: $SIGNATURE"  
+        echo Get TOKEN  
         # Получение JWT токена
         RESPONSE=$(curl --location --request POST 'https://public-api.rustore.ru/public/auth' \
           --header 'Content-Type: application/json' \
@@ -63,15 +67,25 @@ jobs:
             "timestamp": "'"${TIMESTAMP}"'",
             "signature": "'"${SIGNATURE}"'"
           }')
+        # Проверка кода ответа
+        CODE=$(echo $RESPONSE | jq -r '.code')
+        if [ "$CODE" == "error" ]; then
+          echo "Error occurred: $(echo $RESPONSE | jq -r '.message')"
+          exit 1  # Завершение сборки с ошибкой
+        fi
+        echo OK
         # Извлекаем jwe из ответа
         JWT_TOKEN=$(echo $RESPONSE | jq -r '.body.jwe')
         # Публикуем apk
-        APP_PACKAGE_NAME="top.rootu.lampa" # пакет приложения
-        APK_PATH="./app/build/outputs/apk/ruStore/release/app-ruStore-release.apk" # Путь к APK
-        VERSION_CODE=$(git rev-list --count origin/main) # versionCode
-        curl --location --request POST "https://public-api.rustore.ru/public/v1/application/${APP_PACKAGE_NAME}/version/${VERSION_CODE}/apk?servicesType=Unknown&isMainApk=true" \
+        echo Public APK
+        RESPONSE=$(curl --location --request POST "https://public-api.rustore.ru/public/v1/application/${APP_PACKAGE_NAME}/version/${VERSION_CODE}/apk?servicesType=Unknown&isMainApk=true" \
           --header "Public-Token: ${JWT_TOKEN}" \
-          --form "file=@\"${APK_PATH}\""
+          --form "file=@\"${APK_PATH}\"")
+        if [ "$CODE" == "error" ]; then
+          echo "Error occurred: $(echo $RESPONSE | jq -r '.message')"
+          exit 1  # Завершение сборки с ошибкой
+        fi
+        echo OK
     - name: Release
       uses: softprops/action-gh-release@v1
       if: startsWith(github.ref, 'refs/tags/')
